// Copyright (c) 2026 Yize Wu
// SPDX-License-Identifier: MIT

#define GROUP_SIZE 1024

#pragma kernel CalcDepth

uint _SplatCount;
float4x4 _MatrixMV;
StructuredBuffer<float3> _PositionBuffer;
StructuredBuffer<uint> _OrderBuffer;
RWStructuredBuffer<float> _DepthBuffer;

#include "Effects/GsplatEffects.hlsl"

[numthreads(GROUP_SIZE,1,1)]
void CalcDepth(uint3 id : SV_DispatchThreadID)
{
    uint idx = id.x;
    if (idx >= _SplatCount)
        return;

    uint splatId = _OrderBuffer[idx];
    float3 pos = _PositionBuffer[splatId];
    ApplyGsplatEffectPosition(splatId, pos);
    pos = mul(_MatrixMV, float4(pos.xyz, 1)).xyz;
    _DepthBuffer[idx] = pos.z;
}
